### ISSUE TITLE
README.md on cocoapods.org is not updated

### ISSUE THREAD

**Issue by nks5117** [CocoaPods/cocoapods-metadata-service#22]
I use `pod trunk push` to public my pod to cocoapods.org. The README.md is not update when I publish a new version since last month.

Should I submit an issue here? There were no error info when run `pod trunk push`, and everything else works fine, so I can not find where the problem is.

Here is my pod: https://cocoapods.org/pods/KatexUtils, the README showing here is not the current version, but the version number showing on the top is correct.

Source code repo: https://github.com/nks5117/KatexUtils

**Comment by paulb777** [comment]
Based on Firebase releases, the README's stopped updating sometime in March or April 2021

**Comment by orta** [comment]
I think I might have got it, we were uploading fine ( e.g. the latest firebase's README is at http://cocoadocs.org.s3.amazonaws.com/docsets/Firebase/8.6.0/README.html ) but the connection to the database to tell CocoaPods we had updated failed due to heroku SSL changes. Just kinda waiting around for trunk uploads to validate the changes now.

**Comment by orta** [comment]
Confirmed it's now updating the db (as I re-added `updated_at`)

![Screen Shot 2021-08-26 at 9 52 45 PM](https://user-images.githubusercontent.com/49038/131034446-0c769ad8-f792-4cd3-81bf-b0d1ad9ee886.png)

With this rather un-impressive README: https://cocoapods.org/pods/UmoAds
